//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace net.paxialabs.mabe.serviplus.domain.srHistoryODS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://mabe.com/MW/CONFINAL/Mobile/BusquedaODS", ConfigurationName="srHistoryODS.SI_BusquedaODS_OS")]
    public interface SI_BusquedaODS_OS {
        
        // CODEGEN: Generating message contract since the operation SI_BusquedaODS_OS is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        net.paxialabs.mabe.serviplus.domain.srHistoryODS.SI_BusquedaODS_OSResponse SI_BusquedaODS_OS(net.paxialabs.mabe.serviplus.domain.srHistoryODS.SI_BusquedaODS_OSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<net.paxialabs.mabe.serviplus.domain.srHistoryODS.SI_BusquedaODS_OSResponse> SI_BusquedaODS_OSAsync(net.paxialabs.mabe.serviplus.domain.srHistoryODS.SI_BusquedaODS_OSRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mabe.com/MW/CONFINAL/Mobile/BusquedaODS")]
    public partial class DT_BusquedaODS_Out : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DT_BusquedaODS_OutSessionReference sessionReferenceField;
        
        private DT_BusquedaODS_OutDestinoSistema destinoSistemaField;
        
        private DT_BusquedaODS_OutItem[] itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public DT_BusquedaODS_OutSessionReference SessionReference {
            get {
                return this.sessionReferenceField;
            }
            set {
                this.sessionReferenceField = value;
                this.RaisePropertyChanged("SessionReference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public DT_BusquedaODS_OutDestinoSistema DestinoSistema {
            get {
                return this.destinoSistemaField;
            }
            set {
                this.destinoSistemaField = value;
                this.RaisePropertyChanged("DestinoSistema");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public DT_BusquedaODS_OutItem[] Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mabe.com/MW/CONFINAL/Mobile/BusquedaODS")]
    public partial class DT_BusquedaODS_OutSessionReference : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sateliteField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Satelite {
            get {
                return this.sateliteField;
            }
            set {
                this.sateliteField = value;
                this.RaisePropertyChanged("Satelite");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mabe.com/MW/CONFINAL/Mobile/BusquedaODS")]
    public partial class DT_BusquedaODS_OutDestinoSistema : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mandanteField;
        
        private string idiomaField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Mandante {
            get {
                return this.mandanteField;
            }
            set {
                this.mandanteField = value;
                this.RaisePropertyChanged("Mandante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Idioma {
            get {
                return this.idiomaField;
            }
            set {
                this.idiomaField = value;
                this.RaisePropertyChanged("Idioma");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mabe.com/MW/CONFINAL/Mobile/BusquedaODS")]
    public partial class DT_BusquedaODS_OutItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iDConsumidorField;
        
        private string iDBaseInstaladaField;
        
        private string iDOperacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string IDConsumidor {
            get {
                return this.iDConsumidorField;
            }
            set {
                this.iDConsumidorField = value;
                this.RaisePropertyChanged("IDConsumidor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string IDBaseInstalada {
            get {
                return this.iDBaseInstaladaField;
            }
            set {
                this.iDBaseInstaladaField = value;
                this.RaisePropertyChanged("IDBaseInstalada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string IDOperacion {
            get {
                return this.iDOperacionField;
            }
            set {
                this.iDOperacionField = value;
                this.RaisePropertyChanged("IDOperacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mabe.com/MW/CONFINAL/Mobile/BusquedaODS")]
    public partial class DT_BusquedaODS_InItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iD_OperField;
        
        private string estatus_OperField;
        
        private string desc_EstatusField;
        
        private string estatus_VisitaField;
        
        private string desc_Estatus_VisitaField;
        
        private string tipo_ServField;
        
        private string fecha_Cierre_OrdenField;
        
        private string iD_Falla1Field;
        
        private string desc_ID_Falla1Field;
        
        private string iD_Falla2Field;
        
        private string desc_ID_Falla2Field;
        
        private string iD_Falla3Field;
        
        private string desc_ID_Falla3Field;
        
        private string iD_Falla4Field;
        
        private string desc_ID_Falla4Field;
        
        private string iD_Falla5Field;
        
        private string desc_ID_Falla5Field;
        
        private string modeloField;
        
        private string desc_ModeloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ID_Oper {
            get {
                return this.iD_OperField;
            }
            set {
                this.iD_OperField = value;
                this.RaisePropertyChanged("ID_Oper");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Estatus_Oper {
            get {
                return this.estatus_OperField;
            }
            set {
                this.estatus_OperField = value;
                this.RaisePropertyChanged("Estatus_Oper");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Desc_Estatus {
            get {
                return this.desc_EstatusField;
            }
            set {
                this.desc_EstatusField = value;
                this.RaisePropertyChanged("Desc_Estatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Estatus_Visita {
            get {
                return this.estatus_VisitaField;
            }
            set {
                this.estatus_VisitaField = value;
                this.RaisePropertyChanged("Estatus_Visita");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Desc_Estatus_Visita {
            get {
                return this.desc_Estatus_VisitaField;
            }
            set {
                this.desc_Estatus_VisitaField = value;
                this.RaisePropertyChanged("Desc_Estatus_Visita");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Tipo_Serv {
            get {
                return this.tipo_ServField;
            }
            set {
                this.tipo_ServField = value;
                this.RaisePropertyChanged("Tipo_Serv");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Fecha_Cierre_Orden {
            get {
                return this.fecha_Cierre_OrdenField;
            }
            set {
                this.fecha_Cierre_OrdenField = value;
                this.RaisePropertyChanged("Fecha_Cierre_Orden");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string ID_Falla1 {
            get {
                return this.iD_Falla1Field;
            }
            set {
                this.iD_Falla1Field = value;
                this.RaisePropertyChanged("ID_Falla1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Desc_ID_Falla1 {
            get {
                return this.desc_ID_Falla1Field;
            }
            set {
                this.desc_ID_Falla1Field = value;
                this.RaisePropertyChanged("Desc_ID_Falla1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string ID_Falla2 {
            get {
                return this.iD_Falla2Field;
            }
            set {
                this.iD_Falla2Field = value;
                this.RaisePropertyChanged("ID_Falla2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string Desc_ID_Falla2 {
            get {
                return this.desc_ID_Falla2Field;
            }
            set {
                this.desc_ID_Falla2Field = value;
                this.RaisePropertyChanged("Desc_ID_Falla2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string ID_Falla3 {
            get {
                return this.iD_Falla3Field;
            }
            set {
                this.iD_Falla3Field = value;
                this.RaisePropertyChanged("ID_Falla3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string Desc_ID_Falla3 {
            get {
                return this.desc_ID_Falla3Field;
            }
            set {
                this.desc_ID_Falla3Field = value;
                this.RaisePropertyChanged("Desc_ID_Falla3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string ID_Falla4 {
            get {
                return this.iD_Falla4Field;
            }
            set {
                this.iD_Falla4Field = value;
                this.RaisePropertyChanged("ID_Falla4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string Desc_ID_Falla4 {
            get {
                return this.desc_ID_Falla4Field;
            }
            set {
                this.desc_ID_Falla4Field = value;
                this.RaisePropertyChanged("Desc_ID_Falla4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string ID_Falla5 {
            get {
                return this.iD_Falla5Field;
            }
            set {
                this.iD_Falla5Field = value;
                this.RaisePropertyChanged("ID_Falla5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string Desc_ID_Falla5 {
            get {
                return this.desc_ID_Falla5Field;
            }
            set {
                this.desc_ID_Falla5Field = value;
                this.RaisePropertyChanged("Desc_ID_Falla5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string Modelo {
            get {
                return this.modeloField;
            }
            set {
                this.modeloField = value;
                this.RaisePropertyChanged("Modelo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string Desc_Modelo {
            get {
                return this.desc_ModeloField;
            }
            set {
                this.desc_ModeloField = value;
                this.RaisePropertyChanged("Desc_Modelo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_BusquedaODS_OSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mabe.com/MW/CONFINAL/Mobile/BusquedaODS", Order=0)]
        public net.paxialabs.mabe.serviplus.domain.srHistoryODS.DT_BusquedaODS_Out MT_BusquedaODS_Out;
        
        public SI_BusquedaODS_OSRequest() {
        }
        
        public SI_BusquedaODS_OSRequest(net.paxialabs.mabe.serviplus.domain.srHistoryODS.DT_BusquedaODS_Out MT_BusquedaODS_Out) {
            this.MT_BusquedaODS_Out = MT_BusquedaODS_Out;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_BusquedaODS_OSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mabe.com/MW/CONFINAL/Mobile/BusquedaODS", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public net.paxialabs.mabe.serviplus.domain.srHistoryODS.DT_BusquedaODS_InItem[] MT_BusquedaODS_In;
        
        public SI_BusquedaODS_OSResponse() {
        }
        
        public SI_BusquedaODS_OSResponse(net.paxialabs.mabe.serviplus.domain.srHistoryODS.DT_BusquedaODS_InItem[] MT_BusquedaODS_In) {
            this.MT_BusquedaODS_In = MT_BusquedaODS_In;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_BusquedaODS_OSChannel : net.paxialabs.mabe.serviplus.domain.srHistoryODS.SI_BusquedaODS_OS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_BusquedaODS_OSClient : System.ServiceModel.ClientBase<net.paxialabs.mabe.serviplus.domain.srHistoryODS.SI_BusquedaODS_OS>, net.paxialabs.mabe.serviplus.domain.srHistoryODS.SI_BusquedaODS_OS {
        
        public SI_BusquedaODS_OSClient() {
        }
        
        public SI_BusquedaODS_OSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_BusquedaODS_OSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_BusquedaODS_OSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_BusquedaODS_OSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        net.paxialabs.mabe.serviplus.domain.srHistoryODS.SI_BusquedaODS_OSResponse net.paxialabs.mabe.serviplus.domain.srHistoryODS.SI_BusquedaODS_OS.SI_BusquedaODS_OS(net.paxialabs.mabe.serviplus.domain.srHistoryODS.SI_BusquedaODS_OSRequest request) {
            return base.Channel.SI_BusquedaODS_OS(request);
        }
        
        public net.paxialabs.mabe.serviplus.domain.srHistoryODS.DT_BusquedaODS_InItem[] SI_BusquedaODS_OS(net.paxialabs.mabe.serviplus.domain.srHistoryODS.DT_BusquedaODS_Out MT_BusquedaODS_Out) {
            net.paxialabs.mabe.serviplus.domain.srHistoryODS.SI_BusquedaODS_OSRequest inValue = new net.paxialabs.mabe.serviplus.domain.srHistoryODS.SI_BusquedaODS_OSRequest();
            inValue.MT_BusquedaODS_Out = MT_BusquedaODS_Out;
            net.paxialabs.mabe.serviplus.domain.srHistoryODS.SI_BusquedaODS_OSResponse retVal = ((net.paxialabs.mabe.serviplus.domain.srHistoryODS.SI_BusquedaODS_OS)(this)).SI_BusquedaODS_OS(inValue);
            return retVal.MT_BusquedaODS_In;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<net.paxialabs.mabe.serviplus.domain.srHistoryODS.SI_BusquedaODS_OSResponse> net.paxialabs.mabe.serviplus.domain.srHistoryODS.SI_BusquedaODS_OS.SI_BusquedaODS_OSAsync(net.paxialabs.mabe.serviplus.domain.srHistoryODS.SI_BusquedaODS_OSRequest request) {
            return base.Channel.SI_BusquedaODS_OSAsync(request);
        }
        
        public System.Threading.Tasks.Task<net.paxialabs.mabe.serviplus.domain.srHistoryODS.SI_BusquedaODS_OSResponse> SI_BusquedaODS_OSAsync(net.paxialabs.mabe.serviplus.domain.srHistoryODS.DT_BusquedaODS_Out MT_BusquedaODS_Out) {
            net.paxialabs.mabe.serviplus.domain.srHistoryODS.SI_BusquedaODS_OSRequest inValue = new net.paxialabs.mabe.serviplus.domain.srHistoryODS.SI_BusquedaODS_OSRequest();
            inValue.MT_BusquedaODS_Out = MT_BusquedaODS_Out;
            return ((net.paxialabs.mabe.serviplus.domain.srHistoryODS.SI_BusquedaODS_OS)(this)).SI_BusquedaODS_OSAsync(inValue);
        }
    }
}
