//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace net.paxialabs.mabe.serviplus.domain.srHistoryBase {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://mabe.com/MW/CONFINAL/Mobile/BusquedaIB", ConfigurationName="srHistoryBase.SI_BusquedaIB_OS")]
    public interface SI_BusquedaIB_OS {
        
        // CODEGEN: Generating message contract since the operation SI_BusquedaIB_OS is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        net.paxialabs.mabe.serviplus.domain.srHistoryBase.SI_BusquedaIB_OSResponse SI_BusquedaIB_OS(net.paxialabs.mabe.serviplus.domain.srHistoryBase.SI_BusquedaIB_OSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<net.paxialabs.mabe.serviplus.domain.srHistoryBase.SI_BusquedaIB_OSResponse> SI_BusquedaIB_OSAsync(net.paxialabs.mabe.serviplus.domain.srHistoryBase.SI_BusquedaIB_OSRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mabe.com/MW/CONFINAL/Mobile/BusquedaIB")]
    public partial class DT_BaseInstalada_Out : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DT_BaseInstalada_OutSessionReference sessionReferenceField;
        
        private DT_BaseInstalada_OutDestinoSistema destinoSistemaField;
        
        private DT_BaseInstalada_OutItem[] itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public DT_BaseInstalada_OutSessionReference SessionReference {
            get {
                return this.sessionReferenceField;
            }
            set {
                this.sessionReferenceField = value;
                this.RaisePropertyChanged("SessionReference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public DT_BaseInstalada_OutDestinoSistema DestinoSistema {
            get {
                return this.destinoSistemaField;
            }
            set {
                this.destinoSistemaField = value;
                this.RaisePropertyChanged("DestinoSistema");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public DT_BaseInstalada_OutItem[] Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mabe.com/MW/CONFINAL/Mobile/BusquedaIB")]
    public partial class DT_BaseInstalada_OutSessionReference : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sateliteField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Satelite {
            get {
                return this.sateliteField;
            }
            set {
                this.sateliteField = value;
                this.RaisePropertyChanged("Satelite");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mabe.com/MW/CONFINAL/Mobile/BusquedaIB")]
    public partial class DT_BaseInstalada_OutDestinoSistema : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mandanteField;
        
        private string idiomaField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Mandante {
            get {
                return this.mandanteField;
            }
            set {
                this.mandanteField = value;
                this.RaisePropertyChanged("Mandante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Idioma {
            get {
                return this.idiomaField;
            }
            set {
                this.idiomaField = value;
                this.RaisePropertyChanged("Idioma");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mabe.com/MW/CONFINAL/Mobile/BusquedaIB")]
    public partial class DT_BaseInstalada_OutItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iD_ClienteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ID_Cliente {
            get {
                return this.iD_ClienteField;
            }
            set {
                this.iD_ClienteField = value;
                this.RaisePropertyChanged("ID_Cliente");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mabe.com/MW/CONFINAL/Mobile/BusquedaIB")]
    public partial class DT_BaseInstalada_InItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iD_IBField;
        
        private string iD_de_RegistroField;
        
        private string iD_de_ProductoField;
        
        private string marcaField;
        
        private string no_SerieField;
        
        private string fecha_CompraField;
        
        private string gARANTIA_DEField;
        
        private string gARANTIA_AField;
        
        private string lugar_CompraField;
        
        private string grupo_MaterialesField;
        
        private string venta_PolizaField;
        
        private DT_BaseInstalada_InItemRETURN[] rETURNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ID_IB {
            get {
                return this.iD_IBField;
            }
            set {
                this.iD_IBField = value;
                this.RaisePropertyChanged("ID_IB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ID_de_Registro {
            get {
                return this.iD_de_RegistroField;
            }
            set {
                this.iD_de_RegistroField = value;
                this.RaisePropertyChanged("ID_de_Registro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ID_de_Producto {
            get {
                return this.iD_de_ProductoField;
            }
            set {
                this.iD_de_ProductoField = value;
                this.RaisePropertyChanged("ID_de_Producto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Marca {
            get {
                return this.marcaField;
            }
            set {
                this.marcaField = value;
                this.RaisePropertyChanged("Marca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string No_Serie {
            get {
                return this.no_SerieField;
            }
            set {
                this.no_SerieField = value;
                this.RaisePropertyChanged("No_Serie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Fecha_Compra {
            get {
                return this.fecha_CompraField;
            }
            set {
                this.fecha_CompraField = value;
                this.RaisePropertyChanged("Fecha_Compra");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string GARANTIA_DE {
            get {
                return this.gARANTIA_DEField;
            }
            set {
                this.gARANTIA_DEField = value;
                this.RaisePropertyChanged("GARANTIA_DE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string GARANTIA_A {
            get {
                return this.gARANTIA_AField;
            }
            set {
                this.gARANTIA_AField = value;
                this.RaisePropertyChanged("GARANTIA_A");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Lugar_Compra {
            get {
                return this.lugar_CompraField;
            }
            set {
                this.lugar_CompraField = value;
                this.RaisePropertyChanged("Lugar_Compra");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Grupo_Materiales {
            get {
                return this.grupo_MaterialesField;
            }
            set {
                this.grupo_MaterialesField = value;
                this.RaisePropertyChanged("Grupo_Materiales");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string Venta_Poliza {
            get {
                return this.venta_PolizaField;
            }
            set {
                this.venta_PolizaField = value;
                this.RaisePropertyChanged("Venta_Poliza");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RETURN", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public DT_BaseInstalada_InItemRETURN[] RETURN {
            get {
                return this.rETURNField;
            }
            set {
                this.rETURNField = value;
                this.RaisePropertyChanged("RETURN");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mabe.com/MW/CONFINAL/Mobile/BusquedaIB")]
    public partial class DT_BaseInstalada_InItemRETURN : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tIPO_MENSAJEField;
        
        private string cLASE_MENSAJEField;
        
        private string mENSAJEField;
        
        private string dESCRIPCIONField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TIPO_MENSAJE {
            get {
                return this.tIPO_MENSAJEField;
            }
            set {
                this.tIPO_MENSAJEField = value;
                this.RaisePropertyChanged("TIPO_MENSAJE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CLASE_MENSAJE {
            get {
                return this.cLASE_MENSAJEField;
            }
            set {
                this.cLASE_MENSAJEField = value;
                this.RaisePropertyChanged("CLASE_MENSAJE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string MENSAJE {
            get {
                return this.mENSAJEField;
            }
            set {
                this.mENSAJEField = value;
                this.RaisePropertyChanged("MENSAJE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string DESCRIPCION {
            get {
                return this.dESCRIPCIONField;
            }
            set {
                this.dESCRIPCIONField = value;
                this.RaisePropertyChanged("DESCRIPCION");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_BusquedaIB_OSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mabe.com/MW/CONFINAL/BaseInstalada", Order=0)]
        public net.paxialabs.mabe.serviplus.domain.srHistoryBase.DT_BaseInstalada_Out MT_BaseInstalada_Out;
        
        public SI_BusquedaIB_OSRequest() {
        }
        
        public SI_BusquedaIB_OSRequest(net.paxialabs.mabe.serviplus.domain.srHistoryBase.DT_BaseInstalada_Out MT_BaseInstalada_Out) {
            this.MT_BaseInstalada_Out = MT_BaseInstalada_Out;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_BusquedaIB_OSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mabe.com/MW/CONFINAL/BaseInstalada", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public net.paxialabs.mabe.serviplus.domain.srHistoryBase.DT_BaseInstalada_InItem[] MT_BaseInstalada_In;
        
        public SI_BusquedaIB_OSResponse() {
        }
        
        public SI_BusquedaIB_OSResponse(net.paxialabs.mabe.serviplus.domain.srHistoryBase.DT_BaseInstalada_InItem[] MT_BaseInstalada_In) {
            this.MT_BaseInstalada_In = MT_BaseInstalada_In;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_BusquedaIB_OSChannel : net.paxialabs.mabe.serviplus.domain.srHistoryBase.SI_BusquedaIB_OS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_BusquedaIB_OSClient : System.ServiceModel.ClientBase<net.paxialabs.mabe.serviplus.domain.srHistoryBase.SI_BusquedaIB_OS>, net.paxialabs.mabe.serviplus.domain.srHistoryBase.SI_BusquedaIB_OS {
        
        public SI_BusquedaIB_OSClient() {
        }
        
        public SI_BusquedaIB_OSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_BusquedaIB_OSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_BusquedaIB_OSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_BusquedaIB_OSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        net.paxialabs.mabe.serviplus.domain.srHistoryBase.SI_BusquedaIB_OSResponse net.paxialabs.mabe.serviplus.domain.srHistoryBase.SI_BusquedaIB_OS.SI_BusquedaIB_OS(net.paxialabs.mabe.serviplus.domain.srHistoryBase.SI_BusquedaIB_OSRequest request) {
            return base.Channel.SI_BusquedaIB_OS(request);
        }
        
        public net.paxialabs.mabe.serviplus.domain.srHistoryBase.DT_BaseInstalada_InItem[] SI_BusquedaIB_OS(net.paxialabs.mabe.serviplus.domain.srHistoryBase.DT_BaseInstalada_Out MT_BaseInstalada_Out) {
            net.paxialabs.mabe.serviplus.domain.srHistoryBase.SI_BusquedaIB_OSRequest inValue = new net.paxialabs.mabe.serviplus.domain.srHistoryBase.SI_BusquedaIB_OSRequest();
            inValue.MT_BaseInstalada_Out = MT_BaseInstalada_Out;
            net.paxialabs.mabe.serviplus.domain.srHistoryBase.SI_BusquedaIB_OSResponse retVal = ((net.paxialabs.mabe.serviplus.domain.srHistoryBase.SI_BusquedaIB_OS)(this)).SI_BusquedaIB_OS(inValue);
            return retVal.MT_BaseInstalada_In;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<net.paxialabs.mabe.serviplus.domain.srHistoryBase.SI_BusquedaIB_OSResponse> net.paxialabs.mabe.serviplus.domain.srHistoryBase.SI_BusquedaIB_OS.SI_BusquedaIB_OSAsync(net.paxialabs.mabe.serviplus.domain.srHistoryBase.SI_BusquedaIB_OSRequest request) {
            return base.Channel.SI_BusquedaIB_OSAsync(request);
        }
        
        public System.Threading.Tasks.Task<net.paxialabs.mabe.serviplus.domain.srHistoryBase.SI_BusquedaIB_OSResponse> SI_BusquedaIB_OSAsync(net.paxialabs.mabe.serviplus.domain.srHistoryBase.DT_BaseInstalada_Out MT_BaseInstalada_Out) {
            net.paxialabs.mabe.serviplus.domain.srHistoryBase.SI_BusquedaIB_OSRequest inValue = new net.paxialabs.mabe.serviplus.domain.srHistoryBase.SI_BusquedaIB_OSRequest();
            inValue.MT_BaseInstalada_Out = MT_BaseInstalada_Out;
            return ((net.paxialabs.mabe.serviplus.domain.srHistoryBase.SI_BusquedaIB_OS)(this)).SI_BusquedaIB_OSAsync(inValue);
        }
    }
}
