//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace net.paxialabs.mabe.serviplus.domain.srUpdateODS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://mabe.com/MW/CONFINAL/Mobile/ActualizaODS", ConfigurationName="srUpdateODS.SI_ActualizaODS_OS")]
    public interface SI_ActualizaODS_OS {
        
        // CODEGEN: Generating message contract since the operation SI_ActualizaODS_OS is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        net.paxialabs.mabe.serviplus.domain.srUpdateODS.SI_ActualizaODS_OSResponse SI_ActualizaODS_OS(net.paxialabs.mabe.serviplus.domain.srUpdateODS.SI_ActualizaODS_OSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<net.paxialabs.mabe.serviplus.domain.srUpdateODS.SI_ActualizaODS_OSResponse> SI_ActualizaODS_OSAsync(net.paxialabs.mabe.serviplus.domain.srUpdateODS.SI_ActualizaODS_OSRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mabe.com/MW/CONFINAL/Mobile/ActualizaODS")]
    public partial class DT_ActulizaODS_Out : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DT_ActulizaODS_OutSessionReference sessionReferenceField;
        
        private DT_ActulizaODS_OutDestino destinoField;
        
        private DT_ActulizaODS_OutItem[] itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public DT_ActulizaODS_OutSessionReference SessionReference {
            get {
                return this.sessionReferenceField;
            }
            set {
                this.sessionReferenceField = value;
                this.RaisePropertyChanged("SessionReference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public DT_ActulizaODS_OutDestino Destino {
            get {
                return this.destinoField;
            }
            set {
                this.destinoField = value;
                this.RaisePropertyChanged("Destino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public DT_ActulizaODS_OutItem[] Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mabe.com/MW/CONFINAL/Mobile/ActualizaODS")]
    public partial class DT_ActulizaODS_OutSessionReference : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sateliteField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Satelite {
            get {
                return this.sateliteField;
            }
            set {
                this.sateliteField = value;
                this.RaisePropertyChanged("Satelite");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mabe.com/MW/CONFINAL/Mobile/ActualizaODS")]
    public partial class DT_ActulizaODS_OutDestino : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sistemaField;
        
        private string mandanteField;
        
        private string idiomaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Sistema {
            get {
                return this.sistemaField;
            }
            set {
                this.sistemaField = value;
                this.RaisePropertyChanged("Sistema");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Mandante {
            get {
                return this.mandanteField;
            }
            set {
                this.mandanteField = value;
                this.RaisePropertyChanged("Mandante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Idioma {
            get {
                return this.idiomaField;
            }
            set {
                this.idiomaField = value;
                this.RaisePropertyChanged("Idioma");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mabe.com/MW/CONFINAL/Mobile/ActualizaODS")]
    public partial class DT_ActulizaODS_OutItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iD_OperacionField;
        
        private string estatus_Item_VisitaField;
        
        private string tipo_ServField;
        
        private string id_Via_de_PagoField;
        
        private string texto_para_via_pagoField;
        
        private DT_ActulizaODS_OutItemNotas[] notasField;
        
        private string falla_1Field;
        
        private string falla_2Field;
        
        private string falla_3Field;
        
        private string falla_4Field;
        
        private string falla_5Field;
        
        private string monto_CobradoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ID_Operacion {
            get {
                return this.iD_OperacionField;
            }
            set {
                this.iD_OperacionField = value;
                this.RaisePropertyChanged("ID_Operacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Estatus_Item_Visita {
            get {
                return this.estatus_Item_VisitaField;
            }
            set {
                this.estatus_Item_VisitaField = value;
                this.RaisePropertyChanged("Estatus_Item_Visita");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Tipo_Serv {
            get {
                return this.tipo_ServField;
            }
            set {
                this.tipo_ServField = value;
                this.RaisePropertyChanged("Tipo_Serv");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Id_Via_de_Pago {
            get {
                return this.id_Via_de_PagoField;
            }
            set {
                this.id_Via_de_PagoField = value;
                this.RaisePropertyChanged("Id_Via_de_Pago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Texto_para_via_pago {
            get {
                return this.texto_para_via_pagoField;
            }
            set {
                this.texto_para_via_pagoField = value;
                this.RaisePropertyChanged("Texto_para_via_pago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Notas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public DT_ActulizaODS_OutItemNotas[] Notas {
            get {
                return this.notasField;
            }
            set {
                this.notasField = value;
                this.RaisePropertyChanged("Notas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Falla_1 {
            get {
                return this.falla_1Field;
            }
            set {
                this.falla_1Field = value;
                this.RaisePropertyChanged("Falla_1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Falla_2 {
            get {
                return this.falla_2Field;
            }
            set {
                this.falla_2Field = value;
                this.RaisePropertyChanged("Falla_2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Falla_3 {
            get {
                return this.falla_3Field;
            }
            set {
                this.falla_3Field = value;
                this.RaisePropertyChanged("Falla_3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Falla_4 {
            get {
                return this.falla_4Field;
            }
            set {
                this.falla_4Field = value;
                this.RaisePropertyChanged("Falla_4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string Falla_5 {
            get {
                return this.falla_5Field;
            }
            set {
                this.falla_5Field = value;
                this.RaisePropertyChanged("Falla_5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string Monto_Cobrado {
            get {
                return this.monto_CobradoField;
            }
            set {
                this.monto_CobradoField = value;
                this.RaisePropertyChanged("Monto_Cobrado");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mabe.com/MW/CONFINAL/Mobile/ActualizaODS")]
    public partial class DT_ActulizaODS_OutItemNotas : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string clase_de_textoField;
        
        private string textoField;
        
        private string idiomaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Clase_de_texto {
            get {
                return this.clase_de_textoField;
            }
            set {
                this.clase_de_textoField = value;
                this.RaisePropertyChanged("Clase_de_texto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Texto {
            get {
                return this.textoField;
            }
            set {
                this.textoField = value;
                this.RaisePropertyChanged("Texto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Idioma {
            get {
                return this.idiomaField;
            }
            set {
                this.idiomaField = value;
                this.RaisePropertyChanged("Idioma");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mabe.com/MW/CONFINAL/Mobile/ActualizaODS")]
    public partial class DT_ActualizaODS_InItemRETURN : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tIPO_MENSAJEField;
        
        private string cLASE_MENSAJEField;
        
        private string mENSAJEField;
        
        private string dESCRIPCIONField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TIPO_MENSAJE {
            get {
                return this.tIPO_MENSAJEField;
            }
            set {
                this.tIPO_MENSAJEField = value;
                this.RaisePropertyChanged("TIPO_MENSAJE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CLASE_MENSAJE {
            get {
                return this.cLASE_MENSAJEField;
            }
            set {
                this.cLASE_MENSAJEField = value;
                this.RaisePropertyChanged("CLASE_MENSAJE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string MENSAJE {
            get {
                return this.mENSAJEField;
            }
            set {
                this.mENSAJEField = value;
                this.RaisePropertyChanged("MENSAJE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string DESCRIPCION {
            get {
                return this.dESCRIPCIONField;
            }
            set {
                this.dESCRIPCIONField = value;
                this.RaisePropertyChanged("DESCRIPCION");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ActualizaODS_OSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mabe.com/MW/CONFINAL/Mobile/ActualizaODS", Order=0)]
        public net.paxialabs.mabe.serviplus.domain.srUpdateODS.DT_ActulizaODS_Out MT_ActulizaODS_Out;
        
        public SI_ActualizaODS_OSRequest() {
        }
        
        public SI_ActualizaODS_OSRequest(net.paxialabs.mabe.serviplus.domain.srUpdateODS.DT_ActulizaODS_Out MT_ActulizaODS_Out) {
            this.MT_ActulizaODS_Out = MT_ActulizaODS_Out;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_ActualizaODS_OSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mabe.com/MW/CONFINAL/Mobile/ActualizaODS", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("RETURN", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false, NestingLevel=1)]
        public net.paxialabs.mabe.serviplus.domain.srUpdateODS.DT_ActualizaODS_InItemRETURN[][] MT_ActualizaODS_In;
        
        public SI_ActualizaODS_OSResponse() {
        }
        
        public SI_ActualizaODS_OSResponse(net.paxialabs.mabe.serviplus.domain.srUpdateODS.DT_ActualizaODS_InItemRETURN[][] MT_ActualizaODS_In) {
            this.MT_ActualizaODS_In = MT_ActualizaODS_In;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_ActualizaODS_OSChannel : net.paxialabs.mabe.serviplus.domain.srUpdateODS.SI_ActualizaODS_OS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_ActualizaODS_OSClient : System.ServiceModel.ClientBase<net.paxialabs.mabe.serviplus.domain.srUpdateODS.SI_ActualizaODS_OS>, net.paxialabs.mabe.serviplus.domain.srUpdateODS.SI_ActualizaODS_OS {
        
        public SI_ActualizaODS_OSClient() {
        }
        
        public SI_ActualizaODS_OSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_ActualizaODS_OSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_ActualizaODS_OSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_ActualizaODS_OSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        net.paxialabs.mabe.serviplus.domain.srUpdateODS.SI_ActualizaODS_OSResponse net.paxialabs.mabe.serviplus.domain.srUpdateODS.SI_ActualizaODS_OS.SI_ActualizaODS_OS(net.paxialabs.mabe.serviplus.domain.srUpdateODS.SI_ActualizaODS_OSRequest request) {
            return base.Channel.SI_ActualizaODS_OS(request);
        }
        
        public net.paxialabs.mabe.serviplus.domain.srUpdateODS.DT_ActualizaODS_InItemRETURN[][] SI_ActualizaODS_OS(net.paxialabs.mabe.serviplus.domain.srUpdateODS.DT_ActulizaODS_Out MT_ActulizaODS_Out) {
            net.paxialabs.mabe.serviplus.domain.srUpdateODS.SI_ActualizaODS_OSRequest inValue = new net.paxialabs.mabe.serviplus.domain.srUpdateODS.SI_ActualizaODS_OSRequest();
            inValue.MT_ActulizaODS_Out = MT_ActulizaODS_Out;
            net.paxialabs.mabe.serviplus.domain.srUpdateODS.SI_ActualizaODS_OSResponse retVal = ((net.paxialabs.mabe.serviplus.domain.srUpdateODS.SI_ActualizaODS_OS)(this)).SI_ActualizaODS_OS(inValue);
            return retVal.MT_ActualizaODS_In;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<net.paxialabs.mabe.serviplus.domain.srUpdateODS.SI_ActualizaODS_OSResponse> net.paxialabs.mabe.serviplus.domain.srUpdateODS.SI_ActualizaODS_OS.SI_ActualizaODS_OSAsync(net.paxialabs.mabe.serviplus.domain.srUpdateODS.SI_ActualizaODS_OSRequest request) {
            return base.Channel.SI_ActualizaODS_OSAsync(request);
        }
        
        public System.Threading.Tasks.Task<net.paxialabs.mabe.serviplus.domain.srUpdateODS.SI_ActualizaODS_OSResponse> SI_ActualizaODS_OSAsync(net.paxialabs.mabe.serviplus.domain.srUpdateODS.DT_ActulizaODS_Out MT_ActulizaODS_Out) {
            net.paxialabs.mabe.serviplus.domain.srUpdateODS.SI_ActualizaODS_OSRequest inValue = new net.paxialabs.mabe.serviplus.domain.srUpdateODS.SI_ActualizaODS_OSRequest();
            inValue.MT_ActulizaODS_Out = MT_ActulizaODS_Out;
            return ((net.paxialabs.mabe.serviplus.domain.srUpdateODS.SI_ActualizaODS_OS)(this)).SI_ActualizaODS_OSAsync(inValue);
        }
    }
}
