//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace net.paxialabs.mabe.serviplus.domain.srInvoiceODS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://mabe.com/MW/CONFINAL/Facturacion", ConfigurationName="srInvoiceODS.SI_Facturacion_OS")]
    public interface SI_Facturacion_OS {
        
        // CODEGEN: Generating message contract since the operation SI_Facturacion_OS is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        net.paxialabs.mabe.serviplus.domain.srInvoiceODS.SI_Facturacion_OSResponse SI_Facturacion_OS(net.paxialabs.mabe.serviplus.domain.srInvoiceODS.SI_Facturacion_OSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<net.paxialabs.mabe.serviplus.domain.srInvoiceODS.SI_Facturacion_OSResponse> SI_Facturacion_OSAsync(net.paxialabs.mabe.serviplus.domain.srInvoiceODS.SI_Facturacion_OSRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mabe.com/MW/CONFINAL/Facturacion")]
    public partial class DT_Facturacion_Out : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DT_Facturacion_OutSessionReference sessionReferenceField;
        
        private DT_Facturacion_OutDestinoSistema destinoSistemaField;
        
        private DT_Facturacion_OutItem[] itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public DT_Facturacion_OutSessionReference SessionReference {
            get {
                return this.sessionReferenceField;
            }
            set {
                this.sessionReferenceField = value;
                this.RaisePropertyChanged("SessionReference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public DT_Facturacion_OutDestinoSistema DestinoSistema {
            get {
                return this.destinoSistemaField;
            }
            set {
                this.destinoSistemaField = value;
                this.RaisePropertyChanged("DestinoSistema");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public DT_Facturacion_OutItem[] Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mabe.com/MW/CONFINAL/Facturacion")]
    public partial class DT_Facturacion_OutSessionReference : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sateliteField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Satelite {
            get {
                return this.sateliteField;
            }
            set {
                this.sateliteField = value;
                this.RaisePropertyChanged("Satelite");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mabe.com/MW/CONFINAL/Facturacion")]
    public partial class DT_Facturacion_OutDestinoSistema : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mandanteField;
        
        private string idiomaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Mandante {
            get {
                return this.mandanteField;
            }
            set {
                this.mandanteField = value;
                this.RaisePropertyChanged("Mandante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Idioma {
            get {
                return this.idiomaField;
            }
            set {
                this.idiomaField = value;
                this.RaisePropertyChanged("Idioma");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mabe.com/MW/CONFINAL/Facturacion")]
    public partial class DT_Facturacion_OutItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iD_OperacionField;
        
        private DT_Facturacion_OutItemDireccion_de_Facturas[] direccion_de_FacturasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ID_Operacion {
            get {
                return this.iD_OperacionField;
            }
            set {
                this.iD_OperacionField = value;
                this.RaisePropertyChanged("ID_Operacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Direccion_de_Facturas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public DT_Facturacion_OutItemDireccion_de_Facturas[] Direccion_de_Facturas {
            get {
                return this.direccion_de_FacturasField;
            }
            set {
                this.direccion_de_FacturasField = value;
                this.RaisePropertyChanged("Direccion_de_Facturas");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mabe.com/MW/CONFINAL/Facturacion")]
    public partial class DT_Facturacion_OutItemDireccion_de_Facturas : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string addrnumberField;
        
        private string streetField;
        
        private string house_num1Field;
        
        private string house_num2Field;
        
        private string referenciasField;
        
        private string city1Field;
        
        private string city2Field;
        
        private string post_code1Field;
        
        private string regionField;
        
        private string countryField;
        
        private string rFCField;
        
        private string persona_FisicaField;
        
        private string nombreField;
        
        private string apellidoField;
        
        private string razon_socialField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Addrnumber {
            get {
                return this.addrnumberField;
            }
            set {
                this.addrnumberField = value;
                this.RaisePropertyChanged("Addrnumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
                this.RaisePropertyChanged("Street");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string House_num1 {
            get {
                return this.house_num1Field;
            }
            set {
                this.house_num1Field = value;
                this.RaisePropertyChanged("House_num1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string House_num2 {
            get {
                return this.house_num2Field;
            }
            set {
                this.house_num2Field = value;
                this.RaisePropertyChanged("House_num2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Referencias {
            get {
                return this.referenciasField;
            }
            set {
                this.referenciasField = value;
                this.RaisePropertyChanged("Referencias");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string City1 {
            get {
                return this.city1Field;
            }
            set {
                this.city1Field = value;
                this.RaisePropertyChanged("City1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string City2 {
            get {
                return this.city2Field;
            }
            set {
                this.city2Field = value;
                this.RaisePropertyChanged("City2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Post_code1 {
            get {
                return this.post_code1Field;
            }
            set {
                this.post_code1Field = value;
                this.RaisePropertyChanged("Post_code1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
                this.RaisePropertyChanged("Region");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string RFC {
            get {
                return this.rFCField;
            }
            set {
                this.rFCField = value;
                this.RaisePropertyChanged("RFC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string Persona_Fisica {
            get {
                return this.persona_FisicaField;
            }
            set {
                this.persona_FisicaField = value;
                this.RaisePropertyChanged("Persona_Fisica");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string Apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
                this.RaisePropertyChanged("Apellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string Razon_social {
            get {
                return this.razon_socialField;
            }
            set {
                this.razon_socialField = value;
                this.RaisePropertyChanged("Razon_social");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mabe.com/MW/CONFINAL/Mobile/ActualizaODS")]
    public partial class DT_ActualizaODS_InItemRETURN : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tIPO_MENSAJEField;
        
        private string cLASE_MENSAJEField;
        
        private string mENSAJEField;
        
        private string dESCRIPCIONField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TIPO_MENSAJE {
            get {
                return this.tIPO_MENSAJEField;
            }
            set {
                this.tIPO_MENSAJEField = value;
                this.RaisePropertyChanged("TIPO_MENSAJE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CLASE_MENSAJE {
            get {
                return this.cLASE_MENSAJEField;
            }
            set {
                this.cLASE_MENSAJEField = value;
                this.RaisePropertyChanged("CLASE_MENSAJE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string MENSAJE {
            get {
                return this.mENSAJEField;
            }
            set {
                this.mENSAJEField = value;
                this.RaisePropertyChanged("MENSAJE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string DESCRIPCION {
            get {
                return this.dESCRIPCIONField;
            }
            set {
                this.dESCRIPCIONField = value;
                this.RaisePropertyChanged("DESCRIPCION");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_Facturacion_OSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mabe.com/MW/CONFINAL/Facturacion", Order=0)]
        public net.paxialabs.mabe.serviplus.domain.srInvoiceODS.DT_Facturacion_Out MT_Facturacion_Out;
        
        public SI_Facturacion_OSRequest() {
        }
        
        public SI_Facturacion_OSRequest(net.paxialabs.mabe.serviplus.domain.srInvoiceODS.DT_Facturacion_Out MT_Facturacion_Out) {
            this.MT_Facturacion_Out = MT_Facturacion_Out;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_Facturacion_OSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mabe.com/MW/CONFINAL/Facturacion", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("RETURN", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false, NestingLevel=1)]
        public net.paxialabs.mabe.serviplus.domain.srInvoiceODS.DT_ActualizaODS_InItemRETURN[][] MT_Facturacion_In;
        
        public SI_Facturacion_OSResponse() {
        }
        
        public SI_Facturacion_OSResponse(net.paxialabs.mabe.serviplus.domain.srInvoiceODS.DT_ActualizaODS_InItemRETURN[][] MT_Facturacion_In) {
            this.MT_Facturacion_In = MT_Facturacion_In;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_Facturacion_OSChannel : net.paxialabs.mabe.serviplus.domain.srInvoiceODS.SI_Facturacion_OS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_Facturacion_OSClient : System.ServiceModel.ClientBase<net.paxialabs.mabe.serviplus.domain.srInvoiceODS.SI_Facturacion_OS>, net.paxialabs.mabe.serviplus.domain.srInvoiceODS.SI_Facturacion_OS {
        
        public SI_Facturacion_OSClient() {
        }
        
        public SI_Facturacion_OSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_Facturacion_OSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_Facturacion_OSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_Facturacion_OSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        net.paxialabs.mabe.serviplus.domain.srInvoiceODS.SI_Facturacion_OSResponse net.paxialabs.mabe.serviplus.domain.srInvoiceODS.SI_Facturacion_OS.SI_Facturacion_OS(net.paxialabs.mabe.serviplus.domain.srInvoiceODS.SI_Facturacion_OSRequest request) {
            return base.Channel.SI_Facturacion_OS(request);
        }
        
        public net.paxialabs.mabe.serviplus.domain.srInvoiceODS.DT_ActualizaODS_InItemRETURN[][] SI_Facturacion_OS(net.paxialabs.mabe.serviplus.domain.srInvoiceODS.DT_Facturacion_Out MT_Facturacion_Out) {
            net.paxialabs.mabe.serviplus.domain.srInvoiceODS.SI_Facturacion_OSRequest inValue = new net.paxialabs.mabe.serviplus.domain.srInvoiceODS.SI_Facturacion_OSRequest();
            inValue.MT_Facturacion_Out = MT_Facturacion_Out;
            net.paxialabs.mabe.serviplus.domain.srInvoiceODS.SI_Facturacion_OSResponse retVal = ((net.paxialabs.mabe.serviplus.domain.srInvoiceODS.SI_Facturacion_OS)(this)).SI_Facturacion_OS(inValue);
            return retVal.MT_Facturacion_In;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<net.paxialabs.mabe.serviplus.domain.srInvoiceODS.SI_Facturacion_OSResponse> net.paxialabs.mabe.serviplus.domain.srInvoiceODS.SI_Facturacion_OS.SI_Facturacion_OSAsync(net.paxialabs.mabe.serviplus.domain.srInvoiceODS.SI_Facturacion_OSRequest request) {
            return base.Channel.SI_Facturacion_OSAsync(request);
        }
        
        public System.Threading.Tasks.Task<net.paxialabs.mabe.serviplus.domain.srInvoiceODS.SI_Facturacion_OSResponse> SI_Facturacion_OSAsync(net.paxialabs.mabe.serviplus.domain.srInvoiceODS.DT_Facturacion_Out MT_Facturacion_Out) {
            net.paxialabs.mabe.serviplus.domain.srInvoiceODS.SI_Facturacion_OSRequest inValue = new net.paxialabs.mabe.serviplus.domain.srInvoiceODS.SI_Facturacion_OSRequest();
            inValue.MT_Facturacion_Out = MT_Facturacion_Out;
            return ((net.paxialabs.mabe.serviplus.domain.srInvoiceODS.SI_Facturacion_OS)(this)).SI_Facturacion_OSAsync(inValue);
        }
    }
}
