//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace net.paxialabs.mabe.serviplus.data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit
    {
        public int AuditID { get; set; }
        public int UserID { get; set; }
        public int ModuleID { get; set; }
        public System.DateTime DateAudit { get; set; }
        public string Action { get; set; }
    
        public virtual Module Module { get; set; }
        public virtual User User { get; set; }
    }
}
