//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace net.paxialabs.mabe.serviplus.data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeFailureByProduct
    {
        public int FK_CodeFailureID { get; set; }
        public int FK_ProductID { get; set; }
        public Nullable<int> Complexity { get; set; }
        public bool Status { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifyDate { get; set; }
    
        public virtual CodeFailure CodeFailure { get; set; }
        public virtual Product Product { get; set; }
    }
}
