//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace net.paxialabs.mabe.serviplus.data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int PK_HistoryID { get; set; }
        public Nullable<int> FK_InstalledBaseID { get; set; }
        public Nullable<int> FK_ClientID { get; set; }
        public Nullable<int> FK_OrderID { get; set; }
        public string OrderID { get; set; }
        public string OrderStatus { get; set; }
        public string ItemStatus { get; set; }
        public string Guaranty { get; set; }
        public System.DateTime ShopDate { get; set; }
        public System.DateTime CloseDate { get; set; }
        public string FailureID1 { get; set; }
        public string Failure1 { get; set; }
        public string FailureID2 { get; set; }
        public string Failure2 { get; set; }
        public string FailureID3 { get; set; }
        public string Failure3 { get; set; }
        public bool Status { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifyDate { get; set; }
    
        public virtual InstalledBase InstalledBase { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
