//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace net.paxialabs.mabe.serviplus.data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstalledBase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InstalledBase()
        {
            this.History = new HashSet<History>();
            this.Orders = new HashSet<Orders>();
        }
    
        public int PK_InstalledBaseID { get; set; }
        public int FK_ClientID { get; set; }
        public Nullable<int> FK_ProductID { get; set; }
        public Nullable<int> FK_ShopPlaceID { get; set; }
        public string InstalledBaseID { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<System.DateTime> ShopDate { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<bool> ShopPlaceIDFlag { get; set; }
        public Nullable<bool> SerialNumberFlag { get; set; }
        public Nullable<bool> ShopDateFlag { get; set; }
        public Nullable<bool> ProductIDFlag { get; set; }
        public string Model { get; set; }
        public string ProductName { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<History> History { get; set; }
        public virtual Product Product { get; set; }
        public virtual ShopPlace ShopPlace { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
