//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace net.paxialabs.mabe.serviplus.data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int PK_InvoiceID { get; set; }
        public int FK_OrderID { get; set; }
        public string BusinessName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string RFC { get; set; }
        public string Email { get; set; }
        public string CountryAddress { get; set; }
        public string StateAddress { get; set; }
        public string CityAddress { get; set; }
        public string MunicipalityAddress { get; set; }
        public string StreetAddress { get; set; }
        public string NumIntAddress { get; set; }
        public string NumExtAddress { get; set; }
        public string CPAddress { get; set; }
        public bool Status { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public string Location { get; set; }
        public string Reference { get; set; }
        public string PersonType { get; set; }
        public string Folio { get; set; }
        public Nullable<int> FK_TypeQuotation { get; set; }
    
        public virtual Orders Orders { get; set; }
    }
}
