//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace net.paxialabs.mabe.serviplus.data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogMobile
    {
        public int PK_LogMobileID { get; set; }
        public Nullable<int> FK_OrderID { get; set; }
        public Nullable<int> FK_UserID { get; set; }
        public string UserName { get; set; }
        public string Name { get; set; }
        public string OrderID { get; set; }
        public string Module { get; set; }
        public string Message { get; set; }
        public string InnerException { get; set; }
        public string StackTrace { get; set; }
        public string SignType { get; set; }
        public string Battery { get; set; }
        public string SignPercentage { get; set; }
        public string ConnectionType { get; set; }
        public string version { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public bool Status { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public string MobileModel { get; set; }
        public string MobileStorage { get; set; }
    }
}
