//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace net.paxialabs.mabe.serviplus.data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LugarCompra
    {
        public int LugarCompraID { get; set; }
        public string ID_PAIS { get; set; }
        public string ESTADO { get; set; }
        public string IDSucursal { get; set; }
        public string LugarCompra1 { get; set; }
        public string IDClienteDist { get; set; }
        public string Contenedor { get; set; }
        public Nullable<bool> Procesado { get; set; }
        public Nullable<System.DateTime> Creacion { get; set; }
        public Nullable<System.DateTime> Modificacion { get; set; }
    }
}
