//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace net.paxialabs.mabe.serviplus.data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobileSync
    {
        public int PK_MobileSyncID { get; set; }
        public int FK_UserID { get; set; }
        public string UserName { get; set; }
        public string Name { get; set; }
        public string ODS { get; set; }
        public string Type { get; set; }
        public System.DateTime SyncDate { get; set; }
        public bool Status { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifyDate { get; set; }
    }
}
