//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace net.paxialabs.mabe.serviplus.data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleMabe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ModuleMabe()
        {
            this.Employee = new HashSet<Employee>();
        }
    
        public int PK_ModuleID { get; set; }
        public string ModuleID { get; set; }
        public string Region { get; set; }
        public string Module { get; set; }
        public string Base { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string AddressStreet { get; set; }
        public Nullable<int> AddressNumber { get; set; }
        public Nullable<int> AddressCP { get; set; }
        public string AddressColony { get; set; }
        public string AddressCity { get; set; }
        public Nullable<bool> AutorizatedWorkshop { get; set; }
        public Nullable<float> LatWorkshop { get; set; }
        public Nullable<float> LongWorkshop { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employee { get; set; }
    }
}
