//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace net.paxialabs.mabe.serviplus.data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonitorOrders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MonitorOrders()
        {
            this.Evidence = new HashSet<Evidence>();
        }
    
        public int PK_MonitorOrdersID { get; set; }
        public int FK_OrderID { get; set; }
        public Nullable<int> FK_StatusVisitID { get; set; }
        public Nullable<int> FK_StatusOrderID { get; set; }
        public Nullable<int> FK_CauseOrderID { get; set; }
        public Nullable<int> SequenceVisit { get; set; }
        public Nullable<System.DateTime> StartVisitDate { get; set; }
        public Nullable<System.DateTime> EndVisitDate { get; set; }
        public Nullable<System.DateTime> StartOrderDate { get; set; }
        public Nullable<System.DateTime> EndOrderDate { get; set; }
        public Nullable<System.DateTime> StartServiceDate { get; set; }
        public Nullable<System.DateTime> EndServiceDate { get; set; }
        public Nullable<float> LatitudeAddress { get; set; }
        public Nullable<float> LogitudeAddress { get; set; }
        public Nullable<float> LatitudeStartVisit { get; set; }
        public Nullable<float> LogitudeStartVisit { get; set; }
        public Nullable<float> LatitudeEndVisit { get; set; }
        public Nullable<float> LogitudeEndVisit { get; set; }
        public Nullable<float> LatitudeStartOrder { get; set; }
        public Nullable<float> LogitudeStartOrder { get; set; }
        public Nullable<float> LatitudeEndOrder { get; set; }
        public Nullable<float> LogitudeEndOrder { get; set; }
        public Nullable<System.TimeSpan> DurationVisit { get; set; }
        public Nullable<System.TimeSpan> DurationOrder { get; set; }
        public Nullable<System.TimeSpan> DurationExecute { get; set; }
        public Nullable<System.TimeSpan> DurationTransport { get; set; }
        public string NoteVisit { get; set; }
        public string NoteOrder { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<decimal> ExtraKilometrer { get; set; }
    
        public virtual CauseOrder CauseOrder { get; set; }
        public virtual StatusVisit StatusVisit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evidence> Evidence { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
