//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace net.paxialabs.mabe.serviplus.data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ODS
    {
        public int ODSID { get; set; }
        public string IDOrden { get; set; }
        public string IDTecnico { get; set; }
        public string Region { get; set; }
        public string Modulo { get; set; }
        public string ModuloN3 { get; set; }
        public string Base { get; set; }
        public string IDBaseInstalada { get; set; }
        public string Modelo { get; set; }
        public string DescripcionModelo { get; set; }
        public string NumeroSerie { get; set; }
        public string IDLugarCompra { get; set; }
        public string DescripcionLugarCompra { get; set; }
        public string FechaCompra { get; set; }
        public string FechaCreacionODS { get; set; }
        public string FechaProgramacion { get; set; }
        public string HoraProgramacion { get; set; }
        public string Prioridad { get; set; }
        public string TipoServicio { get; set; }
        public string SintomaFalla { get; set; }
        public string Notas { get; set; }
        public string ODS_PADRE { get; set; }
        public string Contenedor { get; set; }
        public Nullable<bool> Procesado { get; set; }
        public Nullable<System.DateTime> Creacion { get; set; }
        public Nullable<System.DateTime> Modificacion { get; set; }
    }
}
