//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace net.paxialabs.mabe.serviplus.data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.Quotation = new HashSet<Quotation>();
            this.ContratReceipt = new HashSet<ContratReceipt>();
            this.Evidence = new HashSet<Evidence>();
            this.History = new HashSet<History>();
            this.Invoice = new HashSet<Invoice>();
            this.LogCRM = new HashSet<LogCRM>();
            this.MonitorOrders = new HashSet<MonitorOrders>();
            this.Payment = new HashSet<Payment>();
            this.Policy = new HashSet<Policy>();
            this.RefSell = new HashSet<RefSell>();
            this.SpareParts = new HashSet<SpareParts>();
        }
    
        public int PK_OrderID { get; set; }
        public int FK_InstalledBaseID { get; set; }
        public int FK_ClientID { get; set; }
        public Nullable<int> FK_EmployeeID { get; set; }
        public Nullable<int> FK_ModuleID { get; set; }
        public Nullable<int> FK_GuarantyID { get; set; }
        public Nullable<int> FK_StatusSchemeID { get; set; }
        public string OrderID { get; set; }
        public string TechnicalID { get; set; }
        public string Symptom { get; set; }
        public string Failure1 { get; set; }
        public string Failure2 { get; set; }
        public string Failure3 { get; set; }
        public string Failure4 { get; set; }
        public string Failure5 { get; set; }
        public string Note { get; set; }
        public Nullable<bool> PreOrder { get; set; }
        public string URLPreOrder { get; set; }
        public bool Status { get; set; }
        public System.DateTime OrderCreateDate { get; set; }
        public System.DateTime OrderExecuteDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string OrderFahter { get; set; }
        public string SendCRM { get; set; }
        public Nullable<bool> ExtraKilometres { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Guaranty Guaranty { get; set; }
        public virtual InstalledBase InstalledBase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quotation> Quotation { get; set; }
        public virtual StatusScheme StatusScheme { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratReceipt> ContratReceipt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evidence> Evidence { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<History> History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogCRM> LogCRM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MonitorOrders> MonitorOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Policy> Policy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RefSell> RefSell { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpareParts> SpareParts { get; set; }
    }
}
