//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace net.paxialabs.mabe.serviplus.data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRECIOS
    {
        public int PrecioID { get; set; }
        public string Material { get; set; }
        public string TipoCondicion { get; set; }
        public string OrganizacionVentas { get; set; }
        public string CanalDistribucion { get; set; }
        public string ListaPrecios { get; set; }
        public string GrupoMaterial1 { get; set; }
        public string GrupoMaterial4 { get; set; }
        public string PrecioMaterial { get; set; }
        public string Moneda { get; set; }
        public string FechaValidez { get; set; }
        public string FechaFinValidez { get; set; }
        public string Contenedor { get; set; }
        public Nullable<bool> Procesado { get; set; }
        public Nullable<System.DateTime> Creacion { get; set; }
        public Nullable<System.DateTime> Modificacion { get; set; }
    }
}
