//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace net.paxialabs.mabe.serviplus.data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefSell
    {
        public int PK_RefSellID { get; set; }
        public int FK_OrderID { get; set; }
        public int FK_ClientID { get; set; }
        public int FK_EmployeeID { get; set; }
        public int FK_PaymentID { get; set; }
        public Nullable<int> FK_Invoice_ID { get; set; }
        public int FK_QuotationID { get; set; }
        public int FK_ProductID { get; set; }
        public Nullable<int> FK_ShopPlace { get; set; }
        public string IDRefSell { get; set; }
        public string OrdenVenta { get; set; }
        public bool Status { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifyDate { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Product Product { get; set; }
        public virtual Quotation Quotation { get; set; }
        public virtual Orders Orders { get; set; }
        public virtual RefSell RefSell1 { get; set; }
        public virtual RefSell RefSell2 { get; set; }
    }
}
