//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace net.paxialabs.mabe.serviplus.data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefsellQuotation
    {
        public int PK_RefsellDetailID { get; set; }
        public int Fk_QuotationID { get; set; }
        public int Fk_ProductID { get; set; }
        public string Cantidad { get; set; }
        public string RefMan { get; set; }
        public string Origen { get; set; }
        public string CostoRef { get; set; }
        public Nullable<bool> Flete { get; set; }
        public string CostoFlete { get; set; }
        public string OrdenVenta { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        public virtual Quotation Quotation { get; set; }
    }
}
