//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace net.paxialabs.mabe.serviplus.data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpareParts
    {
        public int PK_SparePartsID { get; set; }
        public int FK_OrderID { get; set; }
        public Nullable<int> FK_BuildOfMaterialsID { get; set; }
        public Nullable<int> FK_ProductID { get; set; }
        public Nullable<int> FK_WorkforceID { get; set; }
        public string RefManID { get; set; }
        public string SparePartDescription { get; set; }
        public int Quantity { get; set; }
        public Nullable<double> Price { get; set; }
        public string PosicionItem { get; set; }
        public string SparePartStatus { get; set; }
        public string StatusSchema { get; set; }
        public bool Status { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifyDate { get; set; }
    
        public virtual BuildOfMaterials BuildOfMaterials { get; set; }
        public virtual Workforce Workforce { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
