//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace net.paxialabs.mabe.serviplus.data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValidationsSerialNumber
    {
        public int PK_ValidationsSerialNumberID { get; set; }
        public int FK_ModelSerialNumberID { get; set; }
        public string ValidationFormatID { get; set; }
        public string ValidationName { get; set; }
        public int InitialPosition { get; set; }
        public int FinalPosition { get; set; }
        public string Allowed { get; set; }
        public string RankID { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        public virtual ModelSerialNumber ModelSerialNumber { get; set; }
    }
}
