//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace net.paxialabs.mabe.serviplus.domain.srOrdenVenta {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://mabe.com/MW/PEC/COM/OrdenVenta_vTEX", ConfigurationName="srOrdenVenta.SI_OrdenVenta_Out")]
    public interface SI_OrdenVenta_Out {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        net.paxialabs.mabe.serviplus.domain.srOrdenVenta.OrdenVentaClienteSAPResponse OrdenVentaClienteSAP(net.paxialabs.mabe.serviplus.domain.srOrdenVenta.OrdenVentaClienteSAPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        net.paxialabs.mabe.serviplus.domain.srOrdenVenta.OrdenVentaClienteSAPResponse OrdenVentaClienteNoSAP(net.paxialabs.mabe.serviplus.domain.srOrdenVenta.OrdenVentaClienteNoSAPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        net.paxialabs.mabe.serviplus.domain.srOrdenVenta.DesbloqueoEntregaResponse DesbloqueoEntrega(net.paxialabs.mabe.serviplus.domain.srOrdenVenta.DesbloqueoEntregaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mabe.com/MW/PEC/COM/OrdenVenta_vTEX")]
    public partial class DT_OrdenVentaClienteSAP : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string destinoField;
        
        private string sateliteField;
        
        private DT_OrdenVentaClienteSAPItem[] itemField;
        
        public DT_OrdenVentaClienteSAP() {
            this.sateliteField = "VTEX";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Destino {
            get {
                return this.destinoField;
            }
            set {
                this.destinoField = value;
                this.RaisePropertyChanged("Destino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Satelite {
            get {
                return this.sateliteField;
            }
            set {
                this.sateliteField = value;
                this.RaisePropertyChanged("Satelite");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public DT_OrdenVentaClienteSAPItem[] Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mabe.com/MW/PEC/COM/OrdenVenta_vTEX")]
    public partial class DT_OrdenVentaClienteSAPItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ordenWebField;
        
        private string statusBloqueoField;
        
        private string claseDocumentoField;
        
        private string organizacionVentasField;
        
        private string canalDistribucionField;
        
        private string sectorField;
        
        private string numClienteField;
        
        private string funcionInterlocutorSPField;
        
        private string numDestinatarioField;
        
        private string funcionInterlocutorSHField;
        
        private string funcionInterlocutorZ1Field;
        
        private string numeroNotificadoField;
        
        private string funcionInterlocutorZ2Field;
        
        private string numeroConsignadoField;
        
        private string funcionInterlocutorZ4Field;
        
        private string numEjecutivoVentasField;
        
        private string funcionInterlocutorZPField;
        
        private string numProveedorField;
        
        private string numOrdenCompraField;
        
        private string preciosClienteField;
        
        private string fechaCompraField;
        
        private string fechaEntregaField;
        
        private string bloqueoEntregaField;
        
        private string fechaPrecioField;
        
        private string monedaDocField;
        
        private string motivoPedidoField;
        
        private string incoterms1Field;
        
        private string incoterms2Field;
        
        private string condiPagoField;
        
        private string condiEmbarqueField;
        
        private string viaPagoField;
        
        private string clasificacionFiscalField;
        
        private string posicionPedidoField;
        
        private string materialSKUField;
        
        private string cantPedidoField;
        
        private string uniMedidaField;
        
        private string centroField;
        
        private string almacenField;
        
        private string rutaField;
        
        private string numEmpleadoField;
        
        private string nombEmpleadoField;
        
        private DT_OrdenVentaClienteSAPItemClaseCondicion[] claseCondicionField;
        
        private string texCabeceraField;
        
        private string ordenCompraField;
        
        private string adendaClienteField;
        
        private string tipoEmbarqueField;
        
        private string medioEmbarqueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string OrdenWeb {
            get {
                return this.ordenWebField;
            }
            set {
                this.ordenWebField = value;
                this.RaisePropertyChanged("OrdenWeb");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string StatusBloqueo {
            get {
                return this.statusBloqueoField;
            }
            set {
                this.statusBloqueoField = value;
                this.RaisePropertyChanged("StatusBloqueo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ClaseDocumento {
            get {
                return this.claseDocumentoField;
            }
            set {
                this.claseDocumentoField = value;
                this.RaisePropertyChanged("ClaseDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string OrganizacionVentas {
            get {
                return this.organizacionVentasField;
            }
            set {
                this.organizacionVentasField = value;
                this.RaisePropertyChanged("OrganizacionVentas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string CanalDistribucion {
            get {
                return this.canalDistribucionField;
            }
            set {
                this.canalDistribucionField = value;
                this.RaisePropertyChanged("CanalDistribucion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Sector {
            get {
                return this.sectorField;
            }
            set {
                this.sectorField = value;
                this.RaisePropertyChanged("Sector");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string NumCliente {
            get {
                return this.numClienteField;
            }
            set {
                this.numClienteField = value;
                this.RaisePropertyChanged("NumCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string FuncionInterlocutorSP {
            get {
                return this.funcionInterlocutorSPField;
            }
            set {
                this.funcionInterlocutorSPField = value;
                this.RaisePropertyChanged("FuncionInterlocutorSP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string NumDestinatario {
            get {
                return this.numDestinatarioField;
            }
            set {
                this.numDestinatarioField = value;
                this.RaisePropertyChanged("NumDestinatario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string FuncionInterlocutorSH {
            get {
                return this.funcionInterlocutorSHField;
            }
            set {
                this.funcionInterlocutorSHField = value;
                this.RaisePropertyChanged("FuncionInterlocutorSH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string FuncionInterlocutorZ1 {
            get {
                return this.funcionInterlocutorZ1Field;
            }
            set {
                this.funcionInterlocutorZ1Field = value;
                this.RaisePropertyChanged("FuncionInterlocutorZ1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string NumeroNotificado {
            get {
                return this.numeroNotificadoField;
            }
            set {
                this.numeroNotificadoField = value;
                this.RaisePropertyChanged("NumeroNotificado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string FuncionInterlocutorZ2 {
            get {
                return this.funcionInterlocutorZ2Field;
            }
            set {
                this.funcionInterlocutorZ2Field = value;
                this.RaisePropertyChanged("FuncionInterlocutorZ2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string NumeroConsignado {
            get {
                return this.numeroConsignadoField;
            }
            set {
                this.numeroConsignadoField = value;
                this.RaisePropertyChanged("NumeroConsignado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string FuncionInterlocutorZ4 {
            get {
                return this.funcionInterlocutorZ4Field;
            }
            set {
                this.funcionInterlocutorZ4Field = value;
                this.RaisePropertyChanged("FuncionInterlocutorZ4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string NumEjecutivoVentas {
            get {
                return this.numEjecutivoVentasField;
            }
            set {
                this.numEjecutivoVentasField = value;
                this.RaisePropertyChanged("NumEjecutivoVentas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string FuncionInterlocutorZP {
            get {
                return this.funcionInterlocutorZPField;
            }
            set {
                this.funcionInterlocutorZPField = value;
                this.RaisePropertyChanged("FuncionInterlocutorZP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string NumProveedor {
            get {
                return this.numProveedorField;
            }
            set {
                this.numProveedorField = value;
                this.RaisePropertyChanged("NumProveedor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string NumOrdenCompra {
            get {
                return this.numOrdenCompraField;
            }
            set {
                this.numOrdenCompraField = value;
                this.RaisePropertyChanged("NumOrdenCompra");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string PreciosCliente {
            get {
                return this.preciosClienteField;
            }
            set {
                this.preciosClienteField = value;
                this.RaisePropertyChanged("PreciosCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string FechaCompra {
            get {
                return this.fechaCompraField;
            }
            set {
                this.fechaCompraField = value;
                this.RaisePropertyChanged("FechaCompra");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string FechaEntrega {
            get {
                return this.fechaEntregaField;
            }
            set {
                this.fechaEntregaField = value;
                this.RaisePropertyChanged("FechaEntrega");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string BloqueoEntrega {
            get {
                return this.bloqueoEntregaField;
            }
            set {
                this.bloqueoEntregaField = value;
                this.RaisePropertyChanged("BloqueoEntrega");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string FechaPrecio {
            get {
                return this.fechaPrecioField;
            }
            set {
                this.fechaPrecioField = value;
                this.RaisePropertyChanged("FechaPrecio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string MonedaDoc {
            get {
                return this.monedaDocField;
            }
            set {
                this.monedaDocField = value;
                this.RaisePropertyChanged("MonedaDoc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string MotivoPedido {
            get {
                return this.motivoPedidoField;
            }
            set {
                this.motivoPedidoField = value;
                this.RaisePropertyChanged("MotivoPedido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string Incoterms1 {
            get {
                return this.incoterms1Field;
            }
            set {
                this.incoterms1Field = value;
                this.RaisePropertyChanged("Incoterms1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string Incoterms2 {
            get {
                return this.incoterms2Field;
            }
            set {
                this.incoterms2Field = value;
                this.RaisePropertyChanged("Incoterms2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string CondiPago {
            get {
                return this.condiPagoField;
            }
            set {
                this.condiPagoField = value;
                this.RaisePropertyChanged("CondiPago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string CondiEmbarque {
            get {
                return this.condiEmbarqueField;
            }
            set {
                this.condiEmbarqueField = value;
                this.RaisePropertyChanged("CondiEmbarque");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string ViaPago {
            get {
                return this.viaPagoField;
            }
            set {
                this.viaPagoField = value;
                this.RaisePropertyChanged("ViaPago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string ClasificacionFiscal {
            get {
                return this.clasificacionFiscalField;
            }
            set {
                this.clasificacionFiscalField = value;
                this.RaisePropertyChanged("ClasificacionFiscal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string PosicionPedido {
            get {
                return this.posicionPedidoField;
            }
            set {
                this.posicionPedidoField = value;
                this.RaisePropertyChanged("PosicionPedido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string MaterialSKU {
            get {
                return this.materialSKUField;
            }
            set {
                this.materialSKUField = value;
                this.RaisePropertyChanged("MaterialSKU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public string CantPedido {
            get {
                return this.cantPedidoField;
            }
            set {
                this.cantPedidoField = value;
                this.RaisePropertyChanged("CantPedido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public string UniMedida {
            get {
                return this.uniMedidaField;
            }
            set {
                this.uniMedidaField = value;
                this.RaisePropertyChanged("UniMedida");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public string Centro {
            get {
                return this.centroField;
            }
            set {
                this.centroField = value;
                this.RaisePropertyChanged("Centro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=37)]
        public string Almacen {
            get {
                return this.almacenField;
            }
            set {
                this.almacenField = value;
                this.RaisePropertyChanged("Almacen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=38)]
        public string Ruta {
            get {
                return this.rutaField;
            }
            set {
                this.rutaField = value;
                this.RaisePropertyChanged("Ruta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=39)]
        public string NumEmpleado {
            get {
                return this.numEmpleadoField;
            }
            set {
                this.numEmpleadoField = value;
                this.RaisePropertyChanged("NumEmpleado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=40)]
        public string NombEmpleado {
            get {
                return this.nombEmpleadoField;
            }
            set {
                this.nombEmpleadoField = value;
                this.RaisePropertyChanged("NombEmpleado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ClaseCondicion", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=41)]
        public DT_OrdenVentaClienteSAPItemClaseCondicion[] ClaseCondicion {
            get {
                return this.claseCondicionField;
            }
            set {
                this.claseCondicionField = value;
                this.RaisePropertyChanged("ClaseCondicion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=42)]
        public string TexCabecera {
            get {
                return this.texCabeceraField;
            }
            set {
                this.texCabeceraField = value;
                this.RaisePropertyChanged("TexCabecera");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=43)]
        public string OrdenCompra {
            get {
                return this.ordenCompraField;
            }
            set {
                this.ordenCompraField = value;
                this.RaisePropertyChanged("OrdenCompra");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=44)]
        public string AdendaCliente {
            get {
                return this.adendaClienteField;
            }
            set {
                this.adendaClienteField = value;
                this.RaisePropertyChanged("AdendaCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=45)]
        public string TipoEmbarque {
            get {
                return this.tipoEmbarqueField;
            }
            set {
                this.tipoEmbarqueField = value;
                this.RaisePropertyChanged("TipoEmbarque");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=46)]
        public string MedioEmbarque {
            get {
                return this.medioEmbarqueField;
            }
            set {
                this.medioEmbarqueField = value;
                this.RaisePropertyChanged("MedioEmbarque");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mabe.com/MW/PEC/COM/OrdenVenta_vTEX")]
    public partial class DT_OrdenVentaClienteSAPItemClaseCondicion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string claseField;
        
        private string valorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Clase {
            get {
                return this.claseField;
            }
            set {
                this.claseField = value;
                this.RaisePropertyChanged("Clase");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
                this.RaisePropertyChanged("Valor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mabe.com/MW/PEC/COM/OrdenVenta_vTEX")]
    public partial class DT_ConfirmaDesbloqueo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ordenWebField;
        
        private string statusBloqueoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string OrdenWeb {
            get {
                return this.ordenWebField;
            }
            set {
                this.ordenWebField = value;
                this.RaisePropertyChanged("OrdenWeb");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string StatusBloqueo {
            get {
                return this.statusBloqueoField;
            }
            set {
                this.statusBloqueoField = value;
                this.RaisePropertyChanged("StatusBloqueo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mabe.com/MW/PEC/COM/OrdenVenta_vTEX")]
    public partial class DT_DesbloqueoEntrega : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string destinoField;
        
        private string sateliteField;
        
        private string documentoVtaField;
        
        private string ordenWebField;
        
        private string desbloqueoDEntregaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Destino {
            get {
                return this.destinoField;
            }
            set {
                this.destinoField = value;
                this.RaisePropertyChanged("Destino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Satelite {
            get {
                return this.sateliteField;
            }
            set {
                this.sateliteField = value;
                this.RaisePropertyChanged("Satelite");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string DocumentoVta {
            get {
                return this.documentoVtaField;
            }
            set {
                this.documentoVtaField = value;
                this.RaisePropertyChanged("DocumentoVta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string OrdenWeb {
            get {
                return this.ordenWebField;
            }
            set {
                this.ordenWebField = value;
                this.RaisePropertyChanged("OrdenWeb");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string DesbloqueoDEntrega {
            get {
                return this.desbloqueoDEntregaField;
            }
            set {
                this.desbloqueoDEntregaField = value;
                this.RaisePropertyChanged("DesbloqueoDEntrega");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mabe.com/MW/PEC/COM/OrdenVenta_vTEX")]
    public partial class DT_OrdenVentaClienteNoSAP : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string destinoField;
        
        private string sateliteField;
        
        private DT_OrdenVentaClienteNoSAPItem[] itemField;
        
        public DT_OrdenVentaClienteNoSAP() {
            this.sateliteField = "vTEX";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Destino {
            get {
                return this.destinoField;
            }
            set {
                this.destinoField = value;
                this.RaisePropertyChanged("Destino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Satelite {
            get {
                return this.sateliteField;
            }
            set {
                this.sateliteField = value;
                this.RaisePropertyChanged("Satelite");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public DT_OrdenVentaClienteNoSAPItem[] Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mabe.com/MW/PEC/COM/OrdenVenta_vTEX")]
    public partial class DT_OrdenVentaClienteNoSAPItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ordenWebField;
        
        private string aliasNegocioField;
        
        private string claseDocumentoField;
        
        private string organizacionVentasField;
        
        private string canalDistribucionField;
        
        private string sectorField;
        
        private string numClienteField;
        
        private string funcionInterlocutorSPField;
        
        private string numDestinatarioField;
        
        private string funcionInterlocutorSHField;
        
        private string nombreSHField;
        
        private string nombreSH1Field;
        
        private string nombreSH2Field;
        
        private string nombreSH3Field;
        
        private string calleNumField;
        
        private string numInteriorField;
        
        private string numExteriorSupField;
        
        private string coloniaSHField;
        
        private string codigoPostalSHField;
        
        private string delegacionField;
        
        private string paisSHField;
        
        private string regionSHField;
        
        private string telefono1Field;
        
        private string telefono2Field;
        
        private string faxSHField;
        
        private string rFCSHField;
        
        private string emailSHField;
        
        private string funcionInterlocutorZRField;
        
        private string numEjecutivoVentasField;
        
        private string numOrdenCompraField;
        
        private string preciosClienteField;
        
        private string fechaCompraField;
        
        private string fechaEntregaField;
        
        private string bloqueoEntregaField;
        
        private string fechaPrecioField;
        
        private string monedaDocField;
        
        private string motivoPedidoField;
        
        private string incoterms1Field;
        
        private string incoterms2Field;
        
        private string condiPagoField;
        
        private string condiEmbarqueField;
        
        private string viaPagoField;
        
        private string clasificacionFiscalField;
        
        private string posicionPedidoField;
        
        private string materialSKUField;
        
        private string cantPedidoField;
        
        private string uniMedidaField;
        
        private string fechaEntregaItemField;
        
        private string centroField;
        
        private string almacenField;
        
        private string rutaField;
        
        private string numEmpleadoField;
        
        private string nombEmpleadoField;
        
        private string ubicacionEmpleadoField;
        
        private string formaPagoField;
        
        private string texCabeceraField;
        
        private DT_OrdenVentaClienteNoSAPItemClaseCondicion[] claseCondicionField;
        
        private string nombreSHFacField;
        
        private string nombreSH1FacField;
        
        private string calleNumFacField;
        
        private string numInteriorFacField;
        
        private string numExteriorSupFacField;
        
        private string coloniaSHFacField;
        
        private string codigoPostalSHFacField;
        
        private string delegacionFacField;
        
        private string paisSHFacField;
        
        private string regionSHFacField;
        
        private string rFCSHFacField;
        
        private string emailSHFacField;
        
        private string telefono1FacField;
        
        private string telefono2FacField;
        
        private string personaFisicaField;
        
        private string tipoIdentFiscalField;
        
        private string grupoMateriales4Field;
        
        private string grupoCondiciones1Field;
        
        private string tipoListaPreciosField;
        
        private string polizaSNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string OrdenWeb {
            get {
                return this.ordenWebField;
            }
            set {
                this.ordenWebField = value;
                this.RaisePropertyChanged("OrdenWeb");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string AliasNegocio {
            get {
                return this.aliasNegocioField;
            }
            set {
                this.aliasNegocioField = value;
                this.RaisePropertyChanged("AliasNegocio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ClaseDocumento {
            get {
                return this.claseDocumentoField;
            }
            set {
                this.claseDocumentoField = value;
                this.RaisePropertyChanged("ClaseDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string OrganizacionVentas {
            get {
                return this.organizacionVentasField;
            }
            set {
                this.organizacionVentasField = value;
                this.RaisePropertyChanged("OrganizacionVentas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string CanalDistribucion {
            get {
                return this.canalDistribucionField;
            }
            set {
                this.canalDistribucionField = value;
                this.RaisePropertyChanged("CanalDistribucion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Sector {
            get {
                return this.sectorField;
            }
            set {
                this.sectorField = value;
                this.RaisePropertyChanged("Sector");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string NumCliente {
            get {
                return this.numClienteField;
            }
            set {
                this.numClienteField = value;
                this.RaisePropertyChanged("NumCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string FuncionInterlocutorSP {
            get {
                return this.funcionInterlocutorSPField;
            }
            set {
                this.funcionInterlocutorSPField = value;
                this.RaisePropertyChanged("FuncionInterlocutorSP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string NumDestinatario {
            get {
                return this.numDestinatarioField;
            }
            set {
                this.numDestinatarioField = value;
                this.RaisePropertyChanged("NumDestinatario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string FuncionInterlocutorSH {
            get {
                return this.funcionInterlocutorSHField;
            }
            set {
                this.funcionInterlocutorSHField = value;
                this.RaisePropertyChanged("FuncionInterlocutorSH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string NombreSH {
            get {
                return this.nombreSHField;
            }
            set {
                this.nombreSHField = value;
                this.RaisePropertyChanged("NombreSH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string NombreSH1 {
            get {
                return this.nombreSH1Field;
            }
            set {
                this.nombreSH1Field = value;
                this.RaisePropertyChanged("NombreSH1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string NombreSH2 {
            get {
                return this.nombreSH2Field;
            }
            set {
                this.nombreSH2Field = value;
                this.RaisePropertyChanged("NombreSH2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string NombreSH3 {
            get {
                return this.nombreSH3Field;
            }
            set {
                this.nombreSH3Field = value;
                this.RaisePropertyChanged("NombreSH3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string CalleNum {
            get {
                return this.calleNumField;
            }
            set {
                this.calleNumField = value;
                this.RaisePropertyChanged("CalleNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string NumInterior {
            get {
                return this.numInteriorField;
            }
            set {
                this.numInteriorField = value;
                this.RaisePropertyChanged("NumInterior");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string NumExteriorSup {
            get {
                return this.numExteriorSupField;
            }
            set {
                this.numExteriorSupField = value;
                this.RaisePropertyChanged("NumExteriorSup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string ColoniaSH {
            get {
                return this.coloniaSHField;
            }
            set {
                this.coloniaSHField = value;
                this.RaisePropertyChanged("ColoniaSH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string CodigoPostalSH {
            get {
                return this.codigoPostalSHField;
            }
            set {
                this.codigoPostalSHField = value;
                this.RaisePropertyChanged("CodigoPostalSH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string Delegacion {
            get {
                return this.delegacionField;
            }
            set {
                this.delegacionField = value;
                this.RaisePropertyChanged("Delegacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string PaisSH {
            get {
                return this.paisSHField;
            }
            set {
                this.paisSHField = value;
                this.RaisePropertyChanged("PaisSH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string RegionSH {
            get {
                return this.regionSHField;
            }
            set {
                this.regionSHField = value;
                this.RaisePropertyChanged("RegionSH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string Telefono1 {
            get {
                return this.telefono1Field;
            }
            set {
                this.telefono1Field = value;
                this.RaisePropertyChanged("Telefono1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string Telefono2 {
            get {
                return this.telefono2Field;
            }
            set {
                this.telefono2Field = value;
                this.RaisePropertyChanged("Telefono2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string FaxSH {
            get {
                return this.faxSHField;
            }
            set {
                this.faxSHField = value;
                this.RaisePropertyChanged("FaxSH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string RFCSH {
            get {
                return this.rFCSHField;
            }
            set {
                this.rFCSHField = value;
                this.RaisePropertyChanged("RFCSH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string EmailSH {
            get {
                return this.emailSHField;
            }
            set {
                this.emailSHField = value;
                this.RaisePropertyChanged("EmailSH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string FuncionInterlocutorZR {
            get {
                return this.funcionInterlocutorZRField;
            }
            set {
                this.funcionInterlocutorZRField = value;
                this.RaisePropertyChanged("FuncionInterlocutorZR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string NumEjecutivoVentas {
            get {
                return this.numEjecutivoVentasField;
            }
            set {
                this.numEjecutivoVentasField = value;
                this.RaisePropertyChanged("NumEjecutivoVentas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string NumOrdenCompra {
            get {
                return this.numOrdenCompraField;
            }
            set {
                this.numOrdenCompraField = value;
                this.RaisePropertyChanged("NumOrdenCompra");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string PreciosCliente {
            get {
                return this.preciosClienteField;
            }
            set {
                this.preciosClienteField = value;
                this.RaisePropertyChanged("PreciosCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string FechaCompra {
            get {
                return this.fechaCompraField;
            }
            set {
                this.fechaCompraField = value;
                this.RaisePropertyChanged("FechaCompra");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string FechaEntrega {
            get {
                return this.fechaEntregaField;
            }
            set {
                this.fechaEntregaField = value;
                this.RaisePropertyChanged("FechaEntrega");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string BloqueoEntrega {
            get {
                return this.bloqueoEntregaField;
            }
            set {
                this.bloqueoEntregaField = value;
                this.RaisePropertyChanged("BloqueoEntrega");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public string FechaPrecio {
            get {
                return this.fechaPrecioField;
            }
            set {
                this.fechaPrecioField = value;
                this.RaisePropertyChanged("FechaPrecio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public string MonedaDoc {
            get {
                return this.monedaDocField;
            }
            set {
                this.monedaDocField = value;
                this.RaisePropertyChanged("MonedaDoc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public string MotivoPedido {
            get {
                return this.motivoPedidoField;
            }
            set {
                this.motivoPedidoField = value;
                this.RaisePropertyChanged("MotivoPedido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=37)]
        public string Incoterms1 {
            get {
                return this.incoterms1Field;
            }
            set {
                this.incoterms1Field = value;
                this.RaisePropertyChanged("Incoterms1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=38)]
        public string Incoterms2 {
            get {
                return this.incoterms2Field;
            }
            set {
                this.incoterms2Field = value;
                this.RaisePropertyChanged("Incoterms2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=39)]
        public string CondiPago {
            get {
                return this.condiPagoField;
            }
            set {
                this.condiPagoField = value;
                this.RaisePropertyChanged("CondiPago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=40)]
        public string CondiEmbarque {
            get {
                return this.condiEmbarqueField;
            }
            set {
                this.condiEmbarqueField = value;
                this.RaisePropertyChanged("CondiEmbarque");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=41)]
        public string ViaPago {
            get {
                return this.viaPagoField;
            }
            set {
                this.viaPagoField = value;
                this.RaisePropertyChanged("ViaPago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=42)]
        public string ClasificacionFiscal {
            get {
                return this.clasificacionFiscalField;
            }
            set {
                this.clasificacionFiscalField = value;
                this.RaisePropertyChanged("ClasificacionFiscal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=43)]
        public string PosicionPedido {
            get {
                return this.posicionPedidoField;
            }
            set {
                this.posicionPedidoField = value;
                this.RaisePropertyChanged("PosicionPedido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=44)]
        public string MaterialSKU {
            get {
                return this.materialSKUField;
            }
            set {
                this.materialSKUField = value;
                this.RaisePropertyChanged("MaterialSKU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=45)]
        public string CantPedido {
            get {
                return this.cantPedidoField;
            }
            set {
                this.cantPedidoField = value;
                this.RaisePropertyChanged("CantPedido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=46)]
        public string UniMedida {
            get {
                return this.uniMedidaField;
            }
            set {
                this.uniMedidaField = value;
                this.RaisePropertyChanged("UniMedida");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=47)]
        public string FechaEntregaItem {
            get {
                return this.fechaEntregaItemField;
            }
            set {
                this.fechaEntregaItemField = value;
                this.RaisePropertyChanged("FechaEntregaItem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=48)]
        public string Centro {
            get {
                return this.centroField;
            }
            set {
                this.centroField = value;
                this.RaisePropertyChanged("Centro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=49)]
        public string Almacen {
            get {
                return this.almacenField;
            }
            set {
                this.almacenField = value;
                this.RaisePropertyChanged("Almacen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=50)]
        public string Ruta {
            get {
                return this.rutaField;
            }
            set {
                this.rutaField = value;
                this.RaisePropertyChanged("Ruta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=51)]
        public string NumEmpleado {
            get {
                return this.numEmpleadoField;
            }
            set {
                this.numEmpleadoField = value;
                this.RaisePropertyChanged("NumEmpleado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=52)]
        public string NombEmpleado {
            get {
                return this.nombEmpleadoField;
            }
            set {
                this.nombEmpleadoField = value;
                this.RaisePropertyChanged("NombEmpleado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=53)]
        public string UbicacionEmpleado {
            get {
                return this.ubicacionEmpleadoField;
            }
            set {
                this.ubicacionEmpleadoField = value;
                this.RaisePropertyChanged("UbicacionEmpleado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=54)]
        public string FormaPago {
            get {
                return this.formaPagoField;
            }
            set {
                this.formaPagoField = value;
                this.RaisePropertyChanged("FormaPago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=55)]
        public string TexCabecera {
            get {
                return this.texCabeceraField;
            }
            set {
                this.texCabeceraField = value;
                this.RaisePropertyChanged("TexCabecera");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ClaseCondicion", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=56)]
        public DT_OrdenVentaClienteNoSAPItemClaseCondicion[] ClaseCondicion {
            get {
                return this.claseCondicionField;
            }
            set {
                this.claseCondicionField = value;
                this.RaisePropertyChanged("ClaseCondicion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=57)]
        public string NombreSHFac {
            get {
                return this.nombreSHFacField;
            }
            set {
                this.nombreSHFacField = value;
                this.RaisePropertyChanged("NombreSHFac");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=58)]
        public string NombreSH1Fac {
            get {
                return this.nombreSH1FacField;
            }
            set {
                this.nombreSH1FacField = value;
                this.RaisePropertyChanged("NombreSH1Fac");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=59)]
        public string CalleNumFac {
            get {
                return this.calleNumFacField;
            }
            set {
                this.calleNumFacField = value;
                this.RaisePropertyChanged("CalleNumFac");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=60)]
        public string NumInteriorFac {
            get {
                return this.numInteriorFacField;
            }
            set {
                this.numInteriorFacField = value;
                this.RaisePropertyChanged("NumInteriorFac");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=61)]
        public string NumExteriorSupFac {
            get {
                return this.numExteriorSupFacField;
            }
            set {
                this.numExteriorSupFacField = value;
                this.RaisePropertyChanged("NumExteriorSupFac");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=62)]
        public string ColoniaSHFac {
            get {
                return this.coloniaSHFacField;
            }
            set {
                this.coloniaSHFacField = value;
                this.RaisePropertyChanged("ColoniaSHFac");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=63)]
        public string CodigoPostalSHFac {
            get {
                return this.codigoPostalSHFacField;
            }
            set {
                this.codigoPostalSHFacField = value;
                this.RaisePropertyChanged("CodigoPostalSHFac");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=64)]
        public string DelegacionFac {
            get {
                return this.delegacionFacField;
            }
            set {
                this.delegacionFacField = value;
                this.RaisePropertyChanged("DelegacionFac");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=65)]
        public string PaisSHFac {
            get {
                return this.paisSHFacField;
            }
            set {
                this.paisSHFacField = value;
                this.RaisePropertyChanged("PaisSHFac");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=66)]
        public string RegionSHFac {
            get {
                return this.regionSHFacField;
            }
            set {
                this.regionSHFacField = value;
                this.RaisePropertyChanged("RegionSHFac");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=67)]
        public string RFCSHFac {
            get {
                return this.rFCSHFacField;
            }
            set {
                this.rFCSHFacField = value;
                this.RaisePropertyChanged("RFCSHFac");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=68)]
        public string EmailSHFac {
            get {
                return this.emailSHFacField;
            }
            set {
                this.emailSHFacField = value;
                this.RaisePropertyChanged("EmailSHFac");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=69)]
        public string Telefono1Fac {
            get {
                return this.telefono1FacField;
            }
            set {
                this.telefono1FacField = value;
                this.RaisePropertyChanged("Telefono1Fac");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=70)]
        public string Telefono2Fac {
            get {
                return this.telefono2FacField;
            }
            set {
                this.telefono2FacField = value;
                this.RaisePropertyChanged("Telefono2Fac");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=71)]
        public string PersonaFisica {
            get {
                return this.personaFisicaField;
            }
            set {
                this.personaFisicaField = value;
                this.RaisePropertyChanged("PersonaFisica");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=72)]
        public string TipoIdentFiscal {
            get {
                return this.tipoIdentFiscalField;
            }
            set {
                this.tipoIdentFiscalField = value;
                this.RaisePropertyChanged("TipoIdentFiscal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=73)]
        public string GrupoMateriales4 {
            get {
                return this.grupoMateriales4Field;
            }
            set {
                this.grupoMateriales4Field = value;
                this.RaisePropertyChanged("GrupoMateriales4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=74)]
        public string GrupoCondiciones1 {
            get {
                return this.grupoCondiciones1Field;
            }
            set {
                this.grupoCondiciones1Field = value;
                this.RaisePropertyChanged("GrupoCondiciones1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=75)]
        public string TipoListaPrecios {
            get {
                return this.tipoListaPreciosField;
            }
            set {
                this.tipoListaPreciosField = value;
                this.RaisePropertyChanged("TipoListaPrecios");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=76)]
        public string PolizaSN {
            get {
                return this.polizaSNField;
            }
            set {
                this.polizaSNField = value;
                this.RaisePropertyChanged("PolizaSN");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mabe.com/MW/PEC/COM/OrdenVenta_vTEX")]
    public partial class DT_OrdenVentaClienteNoSAPItemClaseCondicion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string claseField;
        
        private string valorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Clase {
            get {
                return this.claseField;
            }
            set {
                this.claseField = value;
                this.RaisePropertyChanged("Clase");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
                this.RaisePropertyChanged("Valor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mabe.com/MW/PEC/COM/OrdenVenta_vTEX")]
    public partial class DT_NumeroOrdenVenta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DT_NumeroOrdenVentaItem[] itemField;
        
        private DT_NumeroOrdenVentaReturn[] returnField;
        
        private DT_NumeroOrdenVentaLog[] logField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public DT_NumeroOrdenVentaItem[] Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public DT_NumeroOrdenVentaReturn[] Return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("Return");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Log", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public DT_NumeroOrdenVentaLog[] Log {
            get {
                return this.logField;
            }
            set {
                this.logField = value;
                this.RaisePropertyChanged("Log");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mabe.com/MW/PEC/COM/OrdenVenta_vTEX")]
    public partial class DT_NumeroOrdenVentaItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ordenWebField;
        
        private string pedidoSAPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string OrdenWeb {
            get {
                return this.ordenWebField;
            }
            set {
                this.ordenWebField = value;
                this.RaisePropertyChanged("OrdenWeb");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string PedidoSAP {
            get {
                return this.pedidoSAPField;
            }
            set {
                this.pedidoSAPField = value;
                this.RaisePropertyChanged("PedidoSAP");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mabe.com/MW/PEC/COM/OrdenVenta_vTEX")]
    public partial class DT_NumeroOrdenVentaReturn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private string idField;
        
        private string numberField;
        
        private string messageField;
        
        private string log_NoField;
        
        private string log_Msg_NoField;
        
        private string message_V1Field;
        
        private string message_V2Field;
        
        private string message_V3Field;
        
        private string message_V4Field;
        
        private string parameterField;
        
        private string rowField;
        
        private string fieldField;
        
        private string systemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Log_No {
            get {
                return this.log_NoField;
            }
            set {
                this.log_NoField = value;
                this.RaisePropertyChanged("Log_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Log_Msg_No {
            get {
                return this.log_Msg_NoField;
            }
            set {
                this.log_Msg_NoField = value;
                this.RaisePropertyChanged("Log_Msg_No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Message_V1 {
            get {
                return this.message_V1Field;
            }
            set {
                this.message_V1Field = value;
                this.RaisePropertyChanged("Message_V1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Message_V2 {
            get {
                return this.message_V2Field;
            }
            set {
                this.message_V2Field = value;
                this.RaisePropertyChanged("Message_V2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Message_V3 {
            get {
                return this.message_V3Field;
            }
            set {
                this.message_V3Field = value;
                this.RaisePropertyChanged("Message_V3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Message_V4 {
            get {
                return this.message_V4Field;
            }
            set {
                this.message_V4Field = value;
                this.RaisePropertyChanged("Message_V4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string Parameter {
            get {
                return this.parameterField;
            }
            set {
                this.parameterField = value;
                this.RaisePropertyChanged("Parameter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string Row {
            get {
                return this.rowField;
            }
            set {
                this.rowField = value;
                this.RaisePropertyChanged("Row");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("Field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string System1 {
            get {
                return this.systemField;
            }
            set {
                this.systemField = value;
                this.RaisePropertyChanged("System");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mabe.com/MW/PEC/COM/OrdenVenta_vTEX")]
    public partial class DT_NumeroOrdenVentaLog : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numPedidoSapField;
        
        private string numItemField;
        
        private string cantidadField;
        
        private string materialField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string NumPedidoSap {
            get {
                return this.numPedidoSapField;
            }
            set {
                this.numPedidoSapField = value;
                this.RaisePropertyChanged("NumPedidoSap");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string NumItem {
            get {
                return this.numItemField;
            }
            set {
                this.numItemField = value;
                this.RaisePropertyChanged("NumItem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("Cantidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Material {
            get {
                return this.materialField;
            }
            set {
                this.materialField = value;
                this.RaisePropertyChanged("Material");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OrdenVentaClienteSAPRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mabe.com/MW/PEC/COM/OrdenVenta_vTEX", Order=0)]
        public net.paxialabs.mabe.serviplus.domain.srOrdenVenta.DT_OrdenVentaClienteSAP MT_OrdenVentaClienteSAP;
        
        public OrdenVentaClienteSAPRequest() {
        }
        
        public OrdenVentaClienteSAPRequest(net.paxialabs.mabe.serviplus.domain.srOrdenVenta.DT_OrdenVentaClienteSAP MT_OrdenVentaClienteSAP) {
            this.MT_OrdenVentaClienteSAP = MT_OrdenVentaClienteSAP;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OrdenVentaClienteSAPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mabe.com/MW/ECC/COM/OrdenVenta_vTEX", Order=0)]
        public net.paxialabs.mabe.serviplus.domain.srOrdenVenta.DT_NumeroOrdenVenta MT_NumeroOrdenVenta;
        
        public OrdenVentaClienteSAPResponse() {
        }
        
        public OrdenVentaClienteSAPResponse(net.paxialabs.mabe.serviplus.domain.srOrdenVenta.DT_NumeroOrdenVenta MT_NumeroOrdenVenta) {
            this.MT_NumeroOrdenVenta = MT_NumeroOrdenVenta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OrdenVentaClienteNoSAPRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mabe.com/MW/PEC/COM/OrdenVenta_vTEX", Order=0)]
        public net.paxialabs.mabe.serviplus.domain.srOrdenVenta.DT_OrdenVentaClienteNoSAP MT_OrdenVentaClienteNoSAP;
        
        public OrdenVentaClienteNoSAPRequest() {
        }
        
        public OrdenVentaClienteNoSAPRequest(net.paxialabs.mabe.serviplus.domain.srOrdenVenta.DT_OrdenVentaClienteNoSAP MT_OrdenVentaClienteNoSAP) {
            this.MT_OrdenVentaClienteNoSAP = MT_OrdenVentaClienteNoSAP;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DesbloqueoEntregaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mabe.com/MW/PEC/COM/OrdenVenta_vTEX", Order=0)]
        public net.paxialabs.mabe.serviplus.domain.srOrdenVenta.DT_DesbloqueoEntrega MT_DesbloqueoEntrega;
        
        public DesbloqueoEntregaRequest() {
        }
        
        public DesbloqueoEntregaRequest(net.paxialabs.mabe.serviplus.domain.srOrdenVenta.DT_DesbloqueoEntrega MT_DesbloqueoEntrega) {
            this.MT_DesbloqueoEntrega = MT_DesbloqueoEntrega;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DesbloqueoEntregaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mabe.com/MW/PEC/COM/OrdenVenta_vTEX", Order=0)]
        public net.paxialabs.mabe.serviplus.domain.srOrdenVenta.DT_ConfirmaDesbloqueo MT_ConfirmaDesbloqueo;
        
        public DesbloqueoEntregaResponse() {
        }
        
        public DesbloqueoEntregaResponse(net.paxialabs.mabe.serviplus.domain.srOrdenVenta.DT_ConfirmaDesbloqueo MT_ConfirmaDesbloqueo) {
            this.MT_ConfirmaDesbloqueo = MT_ConfirmaDesbloqueo;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SI_OrdenVenta_OutChannel : net.paxialabs.mabe.serviplus.domain.srOrdenVenta.SI_OrdenVenta_Out, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SI_OrdenVenta_OutClient : System.ServiceModel.ClientBase<net.paxialabs.mabe.serviplus.domain.srOrdenVenta.SI_OrdenVenta_Out>, net.paxialabs.mabe.serviplus.domain.srOrdenVenta.SI_OrdenVenta_Out {
        
        public SI_OrdenVenta_OutClient() {
        }
        
        public SI_OrdenVenta_OutClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SI_OrdenVenta_OutClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_OrdenVenta_OutClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SI_OrdenVenta_OutClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public net.paxialabs.mabe.serviplus.domain.srOrdenVenta.OrdenVentaClienteSAPResponse OrdenVentaClienteSAP(net.paxialabs.mabe.serviplus.domain.srOrdenVenta.OrdenVentaClienteSAPRequest request) {
            return base.Channel.OrdenVentaClienteSAP(request);
        }
        
        public net.paxialabs.mabe.serviplus.domain.srOrdenVenta.OrdenVentaClienteSAPResponse OrdenVentaClienteNoSAP(net.paxialabs.mabe.serviplus.domain.srOrdenVenta.OrdenVentaClienteNoSAPRequest request) {
            return base.Channel.OrdenVentaClienteNoSAP(request);
        }
        
        public net.paxialabs.mabe.serviplus.domain.srOrdenVenta.DesbloqueoEntregaResponse DesbloqueoEntrega(net.paxialabs.mabe.serviplus.domain.srOrdenVenta.DesbloqueoEntregaRequest request) {
            return base.Channel.DesbloqueoEntrega(request);
        }
    }
}
